### ISSUE TITLE
Error after upgrade Node.js from 18 to 20

### ISSUE THREAD

**Issue by jusfeel** [X-Profiler/xprofiler#235]
```
Node.js v20.10.0
npm 10.2.3
Xprofiler 2.5.3
 
Error: Cannot find module '/apps/test/node_modules/xprofiler/build/binding/Release/node-v115-linux-x64/xprofiler.node'
Require stack:
- /apps/test/node_modules/xprofiler/xprofiler.js
- /apps/test/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/apps/dd4t/node_modules/xprofiler/xprofiler.js:15:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/apps/test/node_modules/xprofiler/xprofiler.js',
    '/apps/test/server.js'
  ]
}
```

`node-v115-linux-x64` folder does not exist.

**Comment by legendecas** [comment]
You'll need to re-install node_modules with `npm install` after switching Node.js versions to download the corresponding xprofiler binary.

**Comment by jusfeel** [comment]
I did. it doesn't help.
